### ISSUE TITLE
Got this error when trying to work on a freshly deleted server still in cache

### ISSUE THREAD

**Issue by moul** [scaleway/scaleway-cli#124]
```console
➜  ~  scw -D exec -w 0ff1ce0f-f1ce-1ff1-ce0f-f1ce0ff1ce0f
DEBU[0000] Waiting for server to be ready
DEBU[0000] GET https://api.scaleway.com/servers/0ff1ce0f-f1ce-1ff1-ce0f-f1ce0ff1ce0f
DEBU[0000] "0ff1ce0f-f1ce-1ff1-ce0f-f1ce0ff1ce0f" not found  Message= StatusCode=0 Type=unknown_resource
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xa24d6]

goroutine 5 [running]:
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerState(0xc208010070, 0xc208097020, 0x24, 0x427430, 0x7, 0x0, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:391 +0x306
github.com/scaleway/scaleway-cli/pkg/api.func·008()
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:416 +0xae
created by github.com/scaleway/scaleway-cli/pkg/api.WaitForServerReady
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:444 +0x255

goroutine 1 [runnable]:
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerReady(0xc208010070, 0xc208097020, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:448 +0x524
github.com/scaleway/scaleway-cli/pkg/commands.RunExec(0x1011d78, 0xc20802c000, 0x1011bf0, 0xc20802c008, 0x1011bf0, 0xc20802c010, 0xc20800c700, 0x38, 0x38, 0xc20800a040, ...)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/commands/exec.go:53 +0x278
github.com/scaleway/scaleway-cli/pkg/cli.runExec(0x61cae0, 0xc20800a040, 0x1, 0x1, 0x0, 0x0)
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/pkg/cli/exec.go:57 +0x1fc
main.main()
	/Users/moul/go/src/github.com/scaleway/scaleway-cli/cmd/scw/main.go:123 +0x7ce

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc2080982c0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080982c0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc
```

---

needs to :

- [x] add a check in the exec function to avoid working with `nil` pointers
- [ ] make 404 http responses print a warning instead of a debug message
- [ ] remove cache entry when running `scw run --rm`

**Comment by moul** [comment]
Fixed in #155
