### ISSUE TITLE
Marshilling email is not working in subscriber resource in lb

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1261]
## How to reproduce:

```
$ go run ./cmd/scw/main.go lb subscriber create name=foobar
panic: could not validate arg value for 'email-config.email': invalid field name 'EmailConfig.email': case is not handled

goroutine 1 [running]:
github.com/scaleway/scaleway-cli/internal/core.validateRequiredArgs(0xc000422620, 0x15c5140, 0xc00058f500, 0xc00024bde0, 0x2, 0x2, 0x101, 0x0)
	/Users/sieben/workspace/scaleway-cli/internal/core/validate.go:82 +0x67d
github.com/scaleway/scaleway-cli/internal/core.DefaultCommandValidateFunc.func1(0xc000422620, 0x15c5140, 0xc00058f500, 0xc00024bde0, 0x2, 0x2, 0x0, 0x0)
	/Users/sieben/workspace/scaleway-cli/internal/core/validate.go:29 +0x96
github.com/scaleway/scaleway-cli/internal/core.run(0x180cfc0, 0xc00041a330, 0xc0004a6000, 0xc000422620, 0xc00024bde0, 0x2, 0x2, 0x1, 0xc00024bde0, 0x2, ...)
	/Users/sieben/workspace/scaleway-cli/internal/core/cobra_utils.go:131 +0x1e1
github.com/scaleway/scaleway-cli/internal/core.cobraRun.func1(0xc0004a6000, 0xc000266670, 0x1, 0x1, 0x0, 0x0)
	/Users/sieben/workspace/scaleway-cli/internal/core/cobra_utils.go:47 +0xa32
github.com/spf13/cobra.(*Command).execute(0xc0004a6000, 0xc000266620, 0x1, 0x1, 0xc0004a6000, 0xc000266620)
	/Users/sieben/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a4a00, 0xc0004240b9, 0x16caa4e, 0x5)
	/Users/sieben/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sieben/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/scaleway/scaleway-cli/internal/core.Bootstrap(0xc0000a3ed0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sieben/workspace/scaleway-cli/internal/core/bootstrap.go:233 +0xc1d
main.main()
	/Users/sieben/workspace/scaleway-cli/cmd/scw/main.go:47 +0x2a5
exit status 2

```

## Version

Version    2.0.0&#43;dev
BuildDate  unknown
GoVersion  go1.14.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by remyleone** [comment]
Subscriber is not a relevant resource for LB
