### ISSUE TITLE
latest node and npm: Cannot find module 'scaleway/node_modules/rc'

### ISSUE THREAD

**Issue by pkoretic** [scaleway/scaleway-cli#263]
```
sudo npm install -g scaleway-cli
/usr/local/bin/scw -> /usr/local/lib/node_modules/scaleway-cli/bin/scw

> ws@0.4.32 install /usr/local/lib/node_modules/scaleway-cli/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/scaleway-cli/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:92: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/local/lib/node_modules/scaleway-cli/node_modules/ws/build'
```
```
scw login --token=XXXXXXXXXXXXXXXXXXX
module.js:328
    throw err;
    ^

Error: Cannot find module 'scaleway/node_modules/rc'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.rc (/usr/local/lib/node_modules/scaleway-cli/lib/utils.js:376:10)
    at Object.module.exports.newApi (/usr/local/lib/node_modules/scaleway-cli/lib/utils.js:364:31)
    at Command.<anonymous> (/usr/local/lib/node_modules/scaleway-cli/lib/program.js:519:24)
    at Command.listener (/usr/local/lib/node_modules/scaleway-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/scaleway-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/scaleway-cli/node_modules/commander/index.js:458:21)
    at /usr/local/lib/node_modules/scaleway-cli/lib/program.js:1039:13
    at /usr/local/lib/node_modules/scaleway-cli/lib/utils.js:30:7
    at null._onTimeout (/usr/local/lib/node_modules/scaleway-cli/node_modules/attempt/lib/attempt.js:105:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

```
npm -v
3.5.3

node -v
v5.4.1
```
```
Linux arch 4.4.0-2-ARCH
```

failed builderror.log
http://pastebin.com/raw/c5a91Sfk

**Comment by moul** [comment]
Hi @pkoretic, thank you for reporting

You try to install the old scaleway-cli in node-js, we are now using a newer version written in Golang.

The old nodejs version moved here: https://github.com/moul/scaleway-cli-node.
It is today only used as a library implementing a Scaleway API client.
But the command-line interface itself is deprecated in favor of the new Golang version (this repository).

If you want to use the CLI, check-out the new [README.md](https://github.com/scaleway/scaleway-cli#scaleway-cli) for instructions, and if you encounter any issue by trying to use the node.js library, please open a new issue here, so I can give a look https://github.com/moul/scaleway-cli-node/issues

Thanks !

**Comment by moul** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.

Thank you!
