### ISSUE TITLE
"scw instance server-type list" fails with "runtime error: invalid memory address" for zone "fr-par-2"

### ISSUE THREAD

**Issue by FredTreg** [scaleway/scaleway-cli#3189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

Configuration (`.config/scw/config.yaml`):
```
...
default_region: fr-par
default_zone: fr-par-2
...
```

`scw instance server-type list`

### Actual Behavior
Output
```
---------------------------------------------------------------------------------------
An error occurred, we are sorry, please consider opening a ticket on github using: 'scw feedback bug'
Give us as many details as possible so we can reproduce the error and fix it.
---------------------------------------------------------------------------------------
runtime error: invalid memory address or nil pointer dereference
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/debug/stack.go:24 +0x65
main.cleanup(0xc0003abdc0)
        /home/runner/work/scaleway-cli/scaleway-cli/cmd/scw/main.go:40 +0xba
panic({0x1610280, 0x25a0400})
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/panic.go:884 +0x212
github.com/scaleway/scaleway-cli/v2/internal/namespaces/instance/v1.serverTypeListBuilder.func1({0x1aeeec0?, 0xc0007c2a80?}, {0x153b5e0?, 0xc00071db80})
        /home/runner/work/scaleway-cli/scaleway-cli/internal/namespaces/instance/v1/custom_server_type.go:105 +0x3b8
github.com/scaleway/scaleway-cli/v2/internal/core.run.func1({0x1aeeec0?, 0xc0007c2a80?}, {0x153b5e0?, 0xc00071db80?})
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/cobra_utils.go:146 +0x38
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdTypeInterceptor({0x1aeeec0, 0xc0007c2a80}, {0x153b5e0?, 0xc00071db80?}, 0x0?)
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:123 +0x35
github.com/scaleway/scaleway-cli/v2/internal/core.combineCommandInterceptor.func1.1({0x1aeeec0?, 0xc0007c2a80?}, {0x0?, 0x0?})
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:30 +0x34
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdErrorInterceptor({0x1aeeec0?, 0xc0007c2a80?}, {0x153b5e0?, 0xc00071db80?}, 0xc00089f7e0?)
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:39 +0x52
github.com/scaleway/scaleway-cli/v2/internal/core.combineCommandInterceptor.func1({0x1aeeec0, 0xc0007c2a80}, {0x153b5e0?, 0xc00071db80?}, 0xc000628930)
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:29 +0xe3
github.com/scaleway/scaleway-cli/v2/internal/core.run({0x1aeeec0, 0xc0007c2a80}, 0xc000012618?, 0xc0001a8140, {0xc0006288d0, 0x1, 0x1})
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/cobra_utils.go:145 +0x26d
github.com/scaleway/scaleway-cli/v2/internal/core.cobraRun.func1(0xc0007fa300?, {0x25fcc20, 0x0, 0x0})
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/cobra_utils.go:43 +0x5bd
github.com/spf13/cobra.(*Command).execute(0xc0007fa300, {0x25fcc20, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000458c00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/scaleway/scaleway-cli/v2/internal/core.Bootstrap(0xc000a0feb8)
        /home/runner/work/scaleway-cli/scaleway-cli/internal/core/bootstrap.go:263 +0x1338
main.main()
        /home/runner/work/scaleway-cli/scaleway-cli/cmd/scw/main.go:72 +0x358

runtime error: invalid memory address or nil pointer dereference
```

## More info

* There is no issue with `scw instance server-type get`
* There is no issue when using `default_zone: fr-par-1`. (I do not have any servers yet in `fr-par-2`, could it be the reason?)

scw version:
```
Version    2.15.0
BuildDate  2023-05-23T09:42:16Z
GoVersion  go1.19.9
GitBranch  HEAD
GitCommit  6b3d42b5
GoArch     amd64
GoOS       linux
```

**Comment by Codelax** [comment]
Hi, thanks for reporting. There seems to be an issue with pagination on one of the used API calls.
Recently the number of server types increased and `fr-par-2` is the most complete zone.
