### ISSUE TITLE
scw init crashes after displaying empty list of project IDs

### ISSUE THREAD

**Issue by davidpfahler** [scaleway/scaleway-cli#3202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw init`

### Expected Behavior

Display a list of project IDs to select from.

### Actual Behavior

Displays two empty lines then crashes when I hit enter or space.

## More info

```
$ scw init

                                                        @@@@@@@@@@@@@@@.
                                                      @@@@@@@@@@@@@@@@@@@@        __          __  _
                                                      @@@               @@@@      \ \        / / | |
                                                      @@@    @@@@@@@     .@@@      \ \  /\  / /__| | ___ ___  _ __ ___   ___
                                                      @@@   @@@@@@@@      @@@       \ \/  \/ / _ \ |/ __/ _ \| '_ ` _ \ / _ \
                                                      @@@   @@@           @@@        \  /\  /  __/ | (_| (_) | | | | | |  __/
                                                      @@@   @@@     @@@   @@@         \/  \/ \___|_|\___\___/|_| |_| |_|\___|
                                                      @@@   @@@     @@@   @@@                                         _  _
                                                      @@@           @@@   @@@                                        | |(_)
                                                      @@@      .@@@@@@@   @@@             ___   ___ __      __   ___ | | _
                                                      @@@      @@@@@@@    @@@            / __| / __|\ \ /\ / /  / __|| || |
                                                       @@@.               @@@            \__ \| (__  \ V  V /  | (__ | || |
                                                        @@@@@@.         .@@@@            |___/ \___|  \_/\_/    \___||_||_|
                                                           @@@@@@@@@@@@@@@@.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Creating new config

Enter a valid secret-key: XXX

Enter a valid access-key: XXX

Choose your default organization ID: XXX

Choose your default project ID


Press enter or space for select.
---------------------------------------------------------------------------------------
An error occurred, we are sorry, please consider opening a ticket on github using: 'scw feedback bug'
Give us as many details as possible so we can reproduce the error and fix it.
---------------------------------------------------------------------------------------
runtime error: index out of range [0] with length 0
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
main.cleanup(0x140001ab1f0)
	github.com/scaleway/scaleway-cli/v2/cmd/scw/main.go:40 +0xb4
panic({0x1021c26e0, 0x14000302f48})
	runtime/panic.go:884 +0x204
github.com/scaleway/scaleway-cli/v2/internal/namespaces/init.promptProjectID({0x10229e360, 0x1400059cc60}, {0x140009194e8, 0x14}, {0x140002f2240, 0x24}, {0x140007c9650, 0x24}, {0x14000047da0, 0x24})
	github.com/scaleway/scaleway-cli/v2/internal/namespaces/init/prompt.go:64 +0x49c
github.com/scaleway/scaleway-cli/v2/internal/namespaces/init.initCommand.func1({0x10229e360, 0x1400059cc60}, {0x101f85320?, 0x140003be300})
	github.com/scaleway/scaleway-cli/v2/internal/namespaces/init/init.go:173 +0x26c
github.com/scaleway/scaleway-cli/v2/internal/core.run.func1({0x10229e360?, 0x1400059cc60?}, {0x101f85320?, 0x140003be300?})
	github.com/scaleway/scaleway-cli/v2/internal/core/cobra_utils.go:151 +0x38
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdTypeInterceptor({0x10229e360, 0x1400059cc60}, {0x101f85320?, 0x140003be300?}, 0x140008674f8?)
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:123 +0x34
github.com/scaleway/scaleway-cli/v2/internal/core.combineCommandInterceptor.func1.1({0x10229e360?, 0x1400059cc60?}, {0x140008674a8?, 0x100d00550?})
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:30 +0x38
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdErrorInterceptor({0x10229e360?, 0x1400059cc60?}, {0x101f85320?, 0x140003be300?}, 0x140008677a8?)
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:39 +0x3c
github.com/scaleway/scaleway-cli/v2/internal/core.combineCommandInterceptor.func1({0x10229e360, 0x1400059cc60}, {0x101f85320?, 0x140003be300?}, 0x140003c4e90)
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:29 +0xec
github.com/scaleway/scaleway-cli/v2/internal/core.run({0x10229e360, 0x1400059cc60}, 0x14000304190?, 0x14000322140, {0x140003c87c0, 0x3, 0x4})
	github.com/scaleway/scaleway-cli/v2/internal/core/cobra_utils.go:150 +0x204
github.com/scaleway/scaleway-cli/v2/internal/core.cobraRun.func1(0x140007ec300?, {0x102da34b0, 0x0, 0x0})
	github.com/scaleway/scaleway-cli/v2/internal/core/cobra_utils.go:43 +0x470
github.com/spf13/cobra.(*Command).execute(0x140007ec300, {0x102da34b0, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400003c900)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/scaleway/scaleway-cli/v2/internal/core.Bootstrap(0x14000867eb0)
	github.com/scaleway/scaleway-cli/v2/internal/core/bootstrap.go:263 +0x1010
main.main()
	github.com/scaleway/scaleway-cli/v2/cmd/scw/main.go:72 +0x364

runtime error: index out of range [0] with length 0
```

**Comment by Codelax** [comment]
Hi, thanks for reporting.
It was fixed with https://github.com/scaleway/scaleway-cli/pull/3201
