### ISSUE TITLE
Error: Cannot find module 'scaleway/node_modules/rc'

### ISSUE THREAD

**Issue by ndarilek** [scaleway/scaleway-cli#346]
```
$ scw version
Client API version: 0.6.0
Node.js version (client): v5.10.1
OS/Arch (client): linux/x64
$ scw login --organization <organization> --token <token>
Error: Cannot find module 'scaleway/node_modules/rc'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.rc (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/lib/utils.js:376:10)
    at Object.module.exports.newApi (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/lib/utils.js:364:31)
    at Command.<anonymous> (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/lib/program.js:519:24)
    at Command.listener (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/node_modules/commander/index.js:458:21)
    at /home/nolan/.node_modules/lib/node_modules/scaleway-cli/lib/program.js:1039:13
    at /home/nolan/.node_modules/lib/node_modules/scaleway-cli/lib/utils.js:30:7
    at Timeout._onTimeout (/home/nolan/.node_modules/lib/node_modules/scaleway-cli/node_modules/attempt/lib/attempt.js:105:15)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

New Scaleway user. Just installed the CLI last night and tried logging in for the first time this afternoon, so I don't think my situation is too unusual. Please let me know if you need any additional details.

Thanks.

**Comment by QuentinPerez** [comment]
Hi @ndarilek 😊,

You tried to install the old scaleway-cli written in Node-js, we are now using a newer version written in Golang.

The Node-js version moved here: https://github.com/moul/scaleway-cli-node. This version is deprecated in favor of the new Golang version.

You can download the precompiled binary [here](https://github.com/scaleway/scaleway-cli/releases)
Or follow the [README instructions](https://github.com/scaleway/scaleway-cli#setup).

Let me know if you need anything else.

**Comment by ndarilek** [comment]
Got it. You may want to put a deprecation note at the top of 
https://blog.scaleway.com/2015/05/20/manage-baremetal-servers-with-scaleway-cli/ 
since that's where I went when I researched CLI options. Thanks!

**Comment by QuentinPerez** [comment]
Hi @ndarilek,

I updated the documentation, thank you 😊
