### ISSUE TITLE
scw instance server-type list -o json crash with `runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by gaetan-craft** [scaleway/scaleway-cli#3752]
## Description:
Scw cli crash randomly when querying list of server type

## How to reproduce:
launch `scw instance server-type list -o json` several times and it often fails

### Command attempted
`scw instance server-type list -o json`
### Expected Behavior
get a json with instance type

### Actual Behavior
```
scw instance server-type list -o json 
---------------------------------------------------------------------------------------
An error occurred, we are sorry, please consider opening a ticket on github using: 'scw feedback bug'
Give us as many details as possible so we can reproduce the error and fix it.
---------------------------------------------------------------------------------------
runtime error: invalid memory address or nil pointer dereference
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x5e
main.cleanup(0xc0003b62a0)
	/home/runner/work/scaleway-cli/scaleway-cli/cmd/scw/main.go:42 +0xca
panic({0x1757b00?, 0x2837be0?})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x21f
github.com/scaleway/scaleway-cli/v2/internal/namespaces/instance/v1.serverTypeListBuilder.func1({0x1c44da0?, 0xc0005f5ad0?}, {0x167bd80?, 0xc0006dfbc0})
	/home/runner/work/scaleway-cli/scaleway-cli/internal/namespaces/instance/v1/custom_server_type.go:105 +0x388
github.com/scaleway/scaleway-cli/v2/internal/core.run.func1({0x1c44da0?, 0xc0005f5ad0?}, {0x167bd80?, 0xc0006dfbc0?})
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/cobra_utils.go:156 +0x32
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdTypeInterceptor({0x1c44da0, 0xc0005f5ad0}, {0x167bd80?, 0xc0006dfbc0?}, 0x4?)
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:123 +0x2f
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3.1({0x1c44da0?, 0xc0005f5ad0?}, {0x410545?, 0x0?})
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:30 +0x31
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdErrorInterceptor({0x1c44da0?, 0xc0005f5ad0?}, {0x167bd80?, 0xc0006dfbc0?}, 0xc0005dd720?)
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:39 +0x46
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3({0x1c44da0, 0xc0005f5ad0}, {0x167bd80?, 0xc0006dfbc0?}, 0xc000515310)
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/command_interceptor.go:29 +0xd6
github.com/scaleway/scaleway-cli/v2/internal/core.run({0x1c44da0, 0xc0005f5ad0}, 0xc000198b20?, 0xc000138a00, {0xc0006df940, 0x1, 0x2})
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/cobra_utils.go:155 +0x3eb
github.com/scaleway/scaleway-cli/v2/internal/core.(*cobraBuilder).hydrateCobra.cobraRun.func3(0xc0006e0800?, {0xc0006df940, 0x0, 0x2})
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/cobra_utils.go:46 +0x5aa
github.com/spf13/cobra.(*Command).execute(0xc0005e8600, {0xc0006df920, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/scaleway/scaleway-cli/v2/internal/core.Bootstrap(0xc000a8fe78)
	/home/runner/work/scaleway-cli/scaleway-cli/internal/core/bootstrap.go:263 +0x12d9
main.main()
	/home/runner/work/scaleway-cli/scaleway-cli/cmd/scw/main.go:74 +0x33f

runtime error: invalid memory address or nil pointer dereference
```

## Version

Version    2.29.0
BuildDate  2024-04-02T15:19:10Z
GoVersion  go1.21.8
GitBranch  HEAD
GitCommit  3c886b5d
GoArch     amd64
GoOS       linux

**Comment by remyleone** [comment]
Hello, I'm sorry but I cannot reproduce on my side. To give me an idea, what was the frequency of failures for this command? On my side, I've launched it many times in a row and it always worked.

**Comment by remyleone** [comment]
I've managed to reproduce your issue! 

```
$ scw instance server-type list -o json zone=fr-par-2
---------------------------------------------------------------------------------------
An error occurred, we are sorry, please consider opening a ticket on github using: 'scw feedback bug'
Give us as many details as possible so we can reproduce the error and fix it.
---------------------------------------------------------------------------------------
runtime error: invalid memory address or nil pointer dereference
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
main.cleanup(0x1400029bf10)
	github.com/scaleway/scaleway-cli/v2/cmd/scw/main.go:42 +0xb4
panic({0x1034f4440?, 0x104327200?})
	runtime/panic.go:770 +0x124
github.com/scaleway/scaleway-cli/v2/internal/namespaces/instance/v1.serverTypeListBuilder.func1({0x10376ccf0?, 0x14000755890?}, {0x103416860, 0x14000701620})
	github.com/scaleway/scaleway-cli/v2/internal/namespaces/instance/v1/custom_server_type.go:105 +0x2e8
github.com/scaleway/scaleway-cli/v2/internal/core.run.func1({0x10376ccf0?, 0x14000755890?}, {0x103416860?, 0x14000701620?})
	github.com/scaleway/scaleway-cli/v2/internal/core/cobra_utils.go:156 +0x38
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdTypeInterceptor({0x10376ccf0, 0x14000755890}, {0x103416860?, 0x14000701620?}, 0x1400066f448?)
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:123 +0x34
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3.1({0x10376ccf0?, 0x14000755890?}, {0x10?, 0x10?})
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:30 +0x38
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdErrorInterceptor({0x10376ccf0?, 0x14000755890?}, {0x103416860?, 0x14000701620?}, 0x10?)
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:39 +0x3c
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3({0x10376ccf0, 0x14000755890}, {0x103416860, 0x14000701620}, 0x140005a4d50)
	github.com/scaleway/scaleway-cli/v2/internal/core/command_interceptor.go:29 +0xb8
github.com/scaleway/scaleway-cli/v2/internal/core.run({0x10376ccf0, 0x14000755890}, 0x140004eac08, 0x140003a8a00, {0x1400060dda0, 0x1, 0x3})
	github.com/scaleway/scaleway-cli/v2/internal/core/cobra_utils.go:155 +0x358
github.com/scaleway/scaleway-cli/v2/internal/core.(*cobraBuilder).hydrateCobra.cobraRun.func3(0x140004eac08, {0x1400060dda0, 0x1, 0x3})
	github.com/scaleway/scaleway-cli/v2/internal/core/cobra_utils.go:46 +0x44c
github.com/spf13/cobra.(*Command).execute(0x140004eac08, {0x1400060dd40, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000240f08)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/scaleway/scaleway-cli/v2/internal/core.Bootstrap(0x1400066fe70)
	github.com/scaleway/scaleway-cli/v2/internal/core/bootstrap.go:263 +0xfec
main.main()
	github.com/scaleway/scaleway-cli/v2/cmd/scw/main.go:74 +0x304

runtime error: invalid memory address or nil pointer dereference%     
```

**Comment by gaetan-craft** [comment]
Sorry Rémy I forgot to say I wan working on fr-par-2 zone

**Comment by remyleone** [comment]
No problem after trying I was able to reproduce it and indeed it only happen for me with fr-par-2 :)
